@startuml

title ** Patron Estrategy para el consumo del combustible**

package Estrategy{
    abstract class ConsumoCombustibleEstrategy{
        + consumoCombustible(): Double
    }
    
    class Barco{
        - consumoCombustible : ConsumoCombustibleEstrategy
    }
    
    class MotorStrategy{}
    class VelaStrategy {}
}

' relaciones

Barco *-- ConsumoCombustibleEstrategy
ConsumoCombustibleEstrategy <|-- MotorStrategy
ConsumoCombustibleEstrategy <|-- VelaStrategy

@enduml